server {
  listen 80;

  location /files/ {
    alias /srv/files/;
    default_type text/plain;
    try_files $uri =404;
  }

  # for adding and deleting files in the system 
  location /api/ {
    proxy_pass http://localhost:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
